"""empty message

Revision ID: 0aaf1e178ae3
Revises: b49b0289aa53
Create Date: 2023-02-28 18:51:11.797852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaf1e178ae3'
down_revision = 'b49b0289aa53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('readme', sa.String(length=500), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=10000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
