"""empty message

Revision ID: 575e0e9e6ed9
Revises: 520272961357
Create Date: 2023-03-11 01:57:02.807340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575e0e9e6ed9'
down_revision = '520272961357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
