"""empty message

Revision ID: d13125a4b5d6
Revises: a8aa1d9b9b46
Create Date: 2023-02-25 16:57:25.575569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13125a4b5d6'
down_revision = 'a8aa1d9b9b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
